# Configuration for Support Requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: support

# Comment to post on issues marked as support requests, `{issue-author}` is an
# optional placeholder. Set to `false` to disable
supportComment: |
  Hi there @{issue-author} :wave:!

  I closed this issue because it was labelled as a support question.

  Please help us organize discussion by posting this on the http://discourse.jupyter.org/ forum.  Support questions often related to multiple Jupyter components or a different component than expected, and thus usually don't receive good answers when posted to a single repository.

  Our goal is to sustain a positive experience for both users and developers. We use GitHub issues for specific discussions related to changing a repository's content, and let the forum be where we can more generally help and inspire each other.

  Thanks you for being an active member of our community! :heart:

# Close issues marked as support requests
close: true

# Lock issues marked as support requests
lock: false

# Assign `off-topic` as the reason for locking. Set to `false` to disable
setLockReason: true

# Repository to extend settings from
# _extends: repo
